name: Nuget pakcage

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://www.nuget.org/packages/KoalaFingers.BasicGuards/
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_ACCESS_TOKEN}}

      - name: Build solution and generate NuGet package
        run: |
          dotnet build -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./src/KoalaFingers.BasicGuards/out/*.nupkg --skip-duplicate --no-symbols true
