name: Nuget package

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04
    name: Update NuGet package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_ACCESS_KEY}}

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore BasicGuards.sln

      - name: Push package
        run: dotnet nuget push ./src/KoalaFingers.BasicGuards/bin/Release/*.nupkg --skip-duplicate --no-symbols true -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
